### ISSUE TITLE
Multiple tags per target confuse "Create Job"

### ISSUE THREAD

**Issue by raphaelcoeffic** [EdgeTX/cloudbuild#30]
When a new job is created on the frontend, it seems that options for targets with multiple tags such as `boxer` are not listed properly, that is, missing options from the first tag (potentially showing only options from the last tag):
```json
    "boxer": {
      "description": "RadioMaster Boxer",
      "tags": [
        "stdlcd",
        "bluetooth"
      ],
      "build_flags": {
        "PCB": "X7",
        "PCBREV": "BOXER"
      }
    },
```

The options from the `stdlcd` tag are missing / not listed on the "Create Job" page:
<img width="367" alt="Screenshot 2023-10-25 at 09 07 11" src="https://github.com/EdgeTX/cloudbuild/assets/1050031/09d8a320-fbec-4846-9a89-1e638967b0c6">

The `stdlcd` options are however displayed for targets that do not define multiple tags. For example:
 <img width="363" alt="Screenshot 2023-10-25 at 09 07 34" src="https://github.com/EdgeTX/cloudbuild/assets/1050031/64e090ba-f197-4978-b6fd-0adf78945152">

**Comment by pfeerick** [comment]
Possibly related is that flags and tags are not integrating properly as one list... i.e. In the cloudbuild section on buddy, the TX16S colorlcd target is showing the extra three languages(CN/JP/TW), but the cloudbuild frontend doesn't.
